"""initial schema — the 16 tables of design/models/orm.py, plus the
Postgres-only objects the ORM docstrings call out.

Copied-model rule: conduit/db/models.py is a verbatim copy of
design/models/orm.py. This migration is generated FROM it and must never be the
place a schema decision is made.

Dialect handling: everything below the auto-generated block is Postgres-only
and is skipped on SQLite (the local profile — see conduit/PROFILES.md). The
statements live in conduit.db.session so that create_all()-based test setup and
Alembic apply exactly the same list.

Revision ID: ba9d07f8c7a3
Revises: 
Create Date: 2026-08-11 01:47:11.965189
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from conduit.db.session import apply_dialect_extras, drop_dialect_extras
from sqlalchemy.dialects import postgresql

revision: str = 'ba9d07f8c7a3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('coordinate_space', sa.Enum('pdf_points', 'raster_px', name='coordinate_space', native_enum=False, length=48), nullable=False),
    sa.Column('srid', sa.Integer(), nullable=False),
    sa.Column('polyline_points', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('bbox_x0', sa.Float(), nullable=False),
    sa.Column('bbox_y0', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('system_type', sa.Enum('conduit', 'cable_tray', 'wire', 'pipe_domestic_water', 'pipe_sanitary', 'pipe_storm', 'pipe_gas', 'pipe_hydronic', 'pipe_sprinkler', 'duct_supply', 'duct_return', 'duct_exhaust', 'unknown', name='system_type', native_enum=False, length=48), nullable=False),
    sa.Column('discipline', sa.Enum('E', 'P', 'M', 'A', 'S', 'FP', 'C', 'G', 'UNKNOWN', name='discipline_meas', native_enum=False, length=48), nullable=False),
    sa.Column('item_class', sa.String(length=128), nullable=True),
    sa.Column('size_label', sa.String(length=64), nullable=True),
    sa.Column('size_inches', sa.Float(), nullable=True),
    sa.Column('size_width_in', sa.Float(), nullable=True),
    sa.Column('size_height_in', sa.Float(), nullable=True),
    sa.Column('size_text_span_id', sa.Uuid(), nullable=True),
    sa.Column('sheet_scale_id', sa.Uuid(), nullable=True),
    sa.Column('scale_ratio_applied', sa.Float(), nullable=False),
    sa.Column('paper_length_pt', sa.Float(), nullable=False),
    sa.Column('horizontal_length_ft', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('vertical_rise_ft', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_length_ft', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rise_source', sa.Enum('none', 'ceiling_height_note', 'riser_diagram', 'rise_symbol', 'floor_to_floor', 'project_default', 'human', name='rise_source', native_enum=False, length=48), nullable=False),
    sa.Column('rise_justification', sa.Text(), nullable=True),
    sa.Column('rise_count', sa.Integer(), nullable=False),
    sa.Column('rise_unit_ft', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rise_evidence_text_span_id', sa.Uuid(), nullable=True),
    sa.Column('rise_evidence_detection_id', sa.Uuid(), nullable=True),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('auto', 'needs_review', 'confirmed', 'rejected', 'manually_added', name='item_status_meas', native_enum=False, length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("vertical_rise_ft = 0 OR rise_source <> 'none'", name='ck_meas_rise_justified'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_meas_conf'),
    sa.CheckConstraint('horizontal_length_ft >= 0', name='ck_meas_horiz_nonneg'),
    sa.CheckConstraint('scale_ratio_applied > 0', name='ck_meas_scale_positive'),
    sa.CheckConstraint('vertical_rise_ft >= 0', name='ck_meas_rise_nonneg'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rise_evidence_detection_id'], ['detection.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rise_evidence_text_span_id'], ['text_span.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_scale_id'], ['sheet_scale.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['size_text_span_id'], ['text_span.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.create_index('ix_measurement_run_sheet', ['pipeline_run_id', 'sheet_id'], unique=False)
        batch_op.create_index('ix_measurement_run_system_size', ['pipeline_run_id', 'system_type', 'size_label'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('bid_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'bidding', 'archived', name='project_status', native_enum=False, length=48), nullable=False),
    sa.Column('defaults', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index('ix_project_status_created', ['status', 'created_at'], unique=False)

    op.create_table('review_action',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.Enum('confirm', 'reject', 'edit_quantity', 'edit_class', 'edit_size', 'edit_geometry', 'add_manual', 'set_scale', 'reclassify_sheet', 'set_rise', 'note', name='review_action_type', native_enum=False, length=48), nullable=False),
    sa.Column('actor_type', sa.Enum('system', 'user', name='actor_type_review', native_enum=False, length=48), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('takeoff_line_id', sa.Uuid(), nullable=True),
    sa.Column('detection_id', sa.Uuid(), nullable=True),
    sa.Column('measurement_id', sa.Uuid(), nullable=True),
    sa.Column('schedule_row_id', sa.Uuid(), nullable=True),
    sa.Column('sheet_id', sa.Uuid(), nullable=True),
    sa.Column('before_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('stable_key', sa.String(length=128), nullable=True),
    sa.Column('carried_forward_from_id', sa.Uuid(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('takeoff_line_id IS NOT NULL OR detection_id IS NOT NULL OR measurement_id IS NOT NULL OR schedule_row_id IS NOT NULL OR sheet_id IS NOT NULL', name='ck_review_has_target'),
    sa.ForeignKeyConstraint(['carried_forward_from_id'], ['review_action.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['detection_id'], ['detection.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurement.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_row_id'], ['schedule_row.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['takeoff_line_id'], ['takeoff_line.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_action', schema=None) as batch_op:
        batch_op.create_index('ix_review_line', ['takeoff_line_id'], unique=False)
        batch_op.create_index('ix_review_run_created', ['pipeline_run_id', 'created_at'], unique=False)
        batch_op.create_index('ix_review_stable_key', ['document_id', 'stable_key'], unique=False)

    op.create_table('sheet_scale',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('viewport_label', sa.String(length=128), nullable=True),
    sa.Column('scale_text', sa.String(length=128), nullable=True),
    sa.Column('scale_ratio', sa.Float(), nullable=False),
    sa.Column('feet_per_paper_point', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('sheet_text', 'title_block', 'graphic_bar', 'calibration', 'human', 'project_default', 'unknown', name='scale_source', native_enum=False, length=48), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('source_text_span_id', sa.Uuid(), nullable=True),
    sa.Column('review_action_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_scale_conf'),
    sa.CheckConstraint('scale_ratio > 0', name='ck_scale_ratio_positive'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_action_id'], ['review_action.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_text_span_id'], ['text_span.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sheet_scale', schema=None) as batch_op:
        batch_op.create_index('uq_sheet_scale_current', ['sheet_id', 'viewport_label'], unique=True, postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))

    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('revision_label', sa.String(length=128), nullable=True),
    sa.Column('uploaded_by', sa.String(length=128), nullable=True),
    sa.Column('current_run_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('page_count > 0', name='ck_document_pages_positive'),
    sa.ForeignKeyConstraint(['current_run_id'], ['pipeline_run.id'], name='fk_document_current_run', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sha256', name='uq_document_project_sha256')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index('ix_document_project', ['project_id'], unique=False)

    op.create_table('pipeline_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('parent_run_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'completed_with_errors', 'failed', 'cancelled', name='run_status', native_enum=False, length=48), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('stages_executed', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inherited_stages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('code_version', sa.String(length=64), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('model_versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('render_dpi', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('progress', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('render_dpi BETWEEN 36 AND 1200', name='ck_run_dpi'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['pipeline_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_run', schema=None) as batch_op:
        batch_op.create_index('ix_run_document_created', ['document_id', 'created_at'], unique=False)
        batch_op.create_index('uq_pipeline_run_current', ['document_id'], unique=True, postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))

    op.create_table('audit_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.Enum('system', 'user', name='actor_type_audit', native_enum=False, length=48), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index('ix_audit_document_seq', ['document_id', 'seq'], unique=False)
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_run_occurred', ['pipeline_run_id', 'occurred_at'], unique=False)

    op.create_table('export_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.Enum('xlsx', 'csv', 'json', name='export_format', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='export_status', native_enum=False, length=48), nullable=False),
    sa.Column('scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('include_audit_sheet', sa.Boolean(), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=True),
    sa.Column('manifest_object_key', sa.String(length=1024), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('evidence_row_count', sa.Integer(), nullable=True),
    sa.Column('model_versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('code_version', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_job', schema=None) as batch_op:
        batch_op.create_index('ix_export_document_created', ['document_id', 'created_at'], unique=False)
        batch_op.create_index('ix_export_run', ['pipeline_run_id'], unique=False)

    op.create_table('sheet',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('sheet_number', sa.String(length=64), nullable=True),
    sa.Column('sheet_title', sa.String(length=512), nullable=True),
    sa.Column('discipline', sa.Enum('E', 'P', 'M', 'A', 'S', 'FP', 'C', 'G', 'UNKNOWN', name='discipline', native_enum=False, length=48), nullable=False),
    sa.Column('subtype', sa.Enum('E_LIGHTING', 'E_POWER', 'E_FIRE_ALARM', 'E_LOW_VOLTAGE', 'E_ONE_LINE', 'E_SCHEDULE', 'E_SITE', 'P_SANITARY', 'P_DOMESTIC_WATER', 'P_GAS', 'P_STORM', 'P_RISER', 'P_SCHEDULE', 'M_DUCT', 'M_PIPING', 'M_EQUIPMENT', 'M_CONTROLS', 'M_SCHEDULE', 'FP_SPRINKLER', 'LEGEND', 'DETAIL', 'COVER', 'OTHER', 'UNKNOWN', name='sheet_subtype', native_enum=False, length=48), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('classification_method', sa.Enum('sheet_number_regex', 'title_block_keywords', 'thumbnail_classifier', 'human', 'default_fallback', name='classification_method', native_enum=False, length=48), nullable=False),
    sa.Column('classification_run_id', sa.Uuid(), nullable=True),
    sa.Column('media_box_x0', sa.Float(), nullable=False),
    sa.Column('media_box_y0', sa.Float(), nullable=False),
    sa.Column('media_box_x1', sa.Float(), nullable=False),
    sa.Column('media_box_y1', sa.Float(), nullable=False),
    sa.Column('rotation_deg', sa.Integer(), nullable=False),
    sa.Column('render_dpi', sa.Integer(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('raster_run_id', sa.Uuid(), nullable=True),
    sa.Column('raster_object_key', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_object_key', sa.String(length=1024), nullable=True),
    sa.Column('tile_base_key', sa.String(length=1024), nullable=True),
    sa.Column('tile_max_zoom', sa.Integer(), nullable=True),
    sa.Column('has_vector_text', sa.Boolean(), nullable=False),
    sa.Column('ocr_applied', sa.Boolean(), nullable=False),
    sa.Column('text_span_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('classification_confidence >= 0.0 AND classification_confidence <= 1.0', name='ck_sheet_class_conf'),
    sa.CheckConstraint('page_number >= 1', name='ck_sheet_page_number'),
    sa.CheckConstraint('render_dpi BETWEEN 36 AND 1200', name='ck_sheet_dpi'),
    sa.CheckConstraint('rotation_deg IN (0, 90, 180, 270)', name='ck_sheet_rotation'),
    sa.ForeignKeyConstraint(['classification_run_id'], ['pipeline_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raster_run_id'], ['pipeline_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_sheet_document_page')
    )
    with op.batch_alter_table('sheet', schema=None) as batch_op:
        batch_op.create_index('ix_sheet_document_discipline', ['document_id', 'discipline'], unique=False)
        batch_op.create_index('ix_sheet_number', ['document_id', 'sheet_number'], unique=False)

    op.create_table('page_task_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('rasterise', 'classify', 'text_index', 'ocr', 'detect', 'measure', 'aggregate', name='stage_name', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', 'skipped', 'inherited', name='task_status', native_enum=False, length=48), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('peak_rss_mb', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_run_id', 'page_number', 'stage', name='uq_page_task_run_page_stage')
    )
    with op.batch_alter_table('page_task_state', schema=None) as batch_op:
        batch_op.create_index('ix_page_task_run_status', ['pipeline_run_id', 'status'], unique=False)

    op.create_table('schedule_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('kind', sa.Enum('lighting_fixture', 'panel', 'electrical_equipment', 'plumbing_fixture', 'mechanical_equipment', 'diffuser', 'valve', 'door', 'other', 'unknown', name='schedule_kind', native_enum=False, length=48), nullable=False),
    sa.Column('coordinate_space', sa.Enum('pdf_points', 'raster_px', name='coordinate_space', native_enum=False, length=48), nullable=False),
    sa.Column('bbox_x0', sa.Float(), nullable=False),
    sa.Column('bbox_y0', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('header_labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('column_x_positions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_sched_table_conf'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_table', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_table_sheet', ['sheet_id'], unique=False)

    op.create_table('takeoff_line',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=True),
    sa.Column('aggregation_key', sa.String(length=512), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('discipline', sa.Enum('E', 'P', 'M', 'A', 'S', 'FP', 'C', 'G', 'UNKNOWN', name='discipline_line', native_enum=False, length=48), nullable=False),
    sa.Column('item_class', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size_label', sa.String(length=64), nullable=True),
    sa.Column('system_type', sa.Enum('conduit', 'cable_tray', 'wire', 'pipe_domestic_water', 'pipe_sanitary', 'pipe_storm', 'pipe_gas', 'pipe_hydronic', 'pipe_sprinkler', 'duct_supply', 'duct_return', 'duct_exhaust', 'unknown', name='system_type_line', native_enum=False, length=48), nullable=True),
    sa.Column('cost_code', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uom', sa.Enum('EA', 'LF', 'SF', 'CF', 'LB', 'HR', 'LOT', name='uom_line', native_enum=False, length=48), nullable=False),
    sa.Column('auto_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('auto', 'needs_review', 'confirmed', 'rejected', 'manually_added', name='item_status_line', native_enum=False, length=48), nullable=False),
    sa.Column('has_override', sa.Boolean(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('contributing_sheet_numbers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("evidence_count > 0 OR status = 'manually_added'", name='ck_line_requires_evidence'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_line_conf'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['takeoff_line.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_run_id', 'aggregation_key', 'revision', name='uq_takeoff_line_key_rev')
    )
    with op.batch_alter_table('takeoff_line', schema=None) as batch_op:
        batch_op.create_index('ix_takeoff_line_doc_disc', ['document_id', 'discipline'], unique=False)
        batch_op.create_index('ix_takeoff_line_run_status', ['pipeline_run_id', 'status'], unique=False)
        batch_op.create_index('uq_takeoff_line_current', ['pipeline_run_id', 'aggregation_key'], unique=True, postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))

    op.create_table('text_span',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.String(length=512), nullable=True),
    sa.Column('coordinate_space', sa.Enum('pdf_points', 'raster_px', name='coordinate_space', native_enum=False, length=48), nullable=False),
    sa.Column('bbox_x0', sa.Float(), nullable=False),
    sa.Column('bbox_y0', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('rotation_deg', sa.Float(), nullable=False),
    sa.Column('font_name', sa.String(length=128), nullable=True),
    sa.Column('font_size_pt', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('vector', 'ocr', 'human', name='text_source', native_enum=False, length=48), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('role', sa.Enum('unknown', 'title_block', 'sheet_number', 'scale_string', 'device_tag', 'equipment_tag', 'size_label', 'dimension', 'schedule_cell', 'room_name', 'note', 'legend_entry', name='span_role', native_enum=False, length=48), nullable=False),
    sa.Column('parsed_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('bbox_x1 >= bbox_x0 AND bbox_y1 >= bbox_y0', name='ck_text_span_bbox'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_text_span_conf'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('text_span', schema=None) as batch_op:
        batch_op.create_index('ix_text_span_normalized', ['normalized_text'], unique=False)
        batch_op.create_index('ix_text_span_run_role', ['pipeline_run_id', 'role'], unique=False)
        batch_op.create_index('ix_text_span_sheet', ['sheet_id'], unique=False)

    op.create_table('detection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('coordinate_space', sa.Enum('pdf_points', 'raster_px', name='coordinate_space', native_enum=False, length=48), nullable=False),
    sa.Column('render_dpi', sa.Integer(), nullable=False),
    sa.Column('bbox_x0', sa.Float(), nullable=False),
    sa.Column('bbox_y0', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('class_name', sa.String(length=128), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('discipline', sa.Enum('E', 'P', 'M', 'A', 'S', 'FP', 'C', 'G', 'UNKNOWN', name='discipline_det', native_enum=False, length=48), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('weights_sha256', sa.String(length=64), nullable=True),
    sa.Column('score_threshold', sa.Float(), nullable=True),
    sa.Column('nms_iou', sa.Float(), nullable=True),
    sa.Column('tile_origin_x', sa.Integer(), nullable=True),
    sa.Column('tile_origin_y', sa.Integer(), nullable=True),
    sa.Column('tile_size_px', sa.Integer(), nullable=True),
    sa.Column('suppressed_by_detection_id', sa.Uuid(), nullable=True),
    sa.Column('matched_text_span_id', sa.Uuid(), nullable=True),
    sa.Column('matched_tag', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('auto', 'needs_review', 'confirmed', 'rejected', 'manually_added', name='item_status_det', native_enum=False, length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('bbox_x1 > bbox_x0 AND bbox_y1 > bbox_y0', name='ck_detection_bbox'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_detection_conf'),
    sa.ForeignKeyConstraint(['matched_text_span_id'], ['text_span.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suppressed_by_detection_id'], ['detection.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection', schema=None) as batch_op:
        batch_op.create_index('ix_detection_run_class', ['pipeline_run_id', 'class_name'], unique=False)
        batch_op.create_index('ix_detection_run_sheet', ['pipeline_run_id', 'sheet_id'], unique=False)
        batch_op.create_index('ix_detection_status', ['pipeline_run_id', 'status'], unique=False)

    op.create_table('schedule_row',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schedule_table_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('cells', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mark', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model_number', sa.String(length=255), nullable=True),
    sa.Column('size_label', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('uom', sa.Enum('EA', 'LF', 'SF', 'CF', 'LB', 'HR', 'LOT', name='uom_sched', native_enum=False, length=48), nullable=True),
    sa.Column('coordinate_space', sa.Enum('pdf_points', 'raster_px', name='coordinate_space', native_enum=False, length=48), nullable=False),
    sa.Column('bbox_x0', sa.Float(), nullable=False),
    sa.Column('bbox_y0', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('auto', 'needs_review', 'confirmed', 'rejected', 'manually_added', name='item_status_sched', native_enum=False, length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_sched_row_conf'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_table_id'], ['schedule_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_table_id', 'row_index', name='uq_schedule_row_index')
    )
    with op.batch_alter_table('schedule_row', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_row_mark', ['pipeline_run_id', 'mark'], unique=False)

    op.create_table('takeoff_line_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('takeoff_line_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_kind', sa.Enum('detection', 'text_span', 'schedule_row', 'measurement', 'manual', name='evidence_kind', native_enum=False, length=48), nullable=False),
    sa.Column('detection_id', sa.Uuid(), nullable=True),
    sa.Column('text_span_id', sa.Uuid(), nullable=True),
    sa.Column('schedule_row_id', sa.Uuid(), nullable=True),
    sa.Column('measurement_id', sa.Uuid(), nullable=True),
    sa.Column('review_action_id', sa.Uuid(), nullable=True),
    sa.Column('contribution_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('coordinate_space', sa.Enum('pdf_points', 'raster_px', name='coordinate_space_ev', native_enum=False, length=48), nullable=True),
    sa.Column('bbox_x0', sa.Float(), nullable=True),
    sa.Column('bbox_y0', sa.Float(), nullable=True),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extractor_version', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(CASE WHEN detection_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN text_span_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN schedule_row_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN measurement_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN review_action_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_evidence_exactly_one'),
    sa.ForeignKeyConstraint(['detection_id'], ['detection.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurement.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_action_id'], ['review_action.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_row_id'], ['schedule_row.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['takeoff_line_id'], ['takeoff_line.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_span_id'], ['text_span.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('takeoff_line_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_detection', ['detection_id'], unique=False)
        batch_op.create_index('ix_evidence_line', ['takeoff_line_id'], unique=False)
        batch_op.create_index('ix_evidence_measurement', ['measurement_id'], unique=False)

    # ### end Alembic commands ###

    # --- Postgres-only extras (no-ops on SQLite) -------------------------
    # 1. pg_trgm GIN index on text_span.normalized_text  (models.py ~L733)
    # 2. audit_event_seq_seq sequence for audit_event.seq (models.py ~L1315)
    apply_dialect_extras(op.get_bind())


def downgrade() -> None:
    drop_dialect_extras(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('takeoff_line_evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_measurement')
        batch_op.drop_index('ix_evidence_line')
        batch_op.drop_index('ix_evidence_detection')

    op.drop_table('takeoff_line_evidence')
    with op.batch_alter_table('schedule_row', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_row_mark')

    op.drop_table('schedule_row')
    with op.batch_alter_table('detection', schema=None) as batch_op:
        batch_op.drop_index('ix_detection_status')
        batch_op.drop_index('ix_detection_run_sheet')
        batch_op.drop_index('ix_detection_run_class')

    op.drop_table('detection')
    with op.batch_alter_table('text_span', schema=None) as batch_op:
        batch_op.drop_index('ix_text_span_sheet')
        batch_op.drop_index('ix_text_span_run_role')
        batch_op.drop_index('ix_text_span_normalized')

    op.drop_table('text_span')
    with op.batch_alter_table('takeoff_line', schema=None) as batch_op:
        batch_op.drop_index('uq_takeoff_line_current', postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))
        batch_op.drop_index('ix_takeoff_line_run_status')
        batch_op.drop_index('ix_takeoff_line_doc_disc')

    op.drop_table('takeoff_line')
    with op.batch_alter_table('schedule_table', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_table_sheet')

    op.drop_table('schedule_table')
    with op.batch_alter_table('page_task_state', schema=None) as batch_op:
        batch_op.drop_index('ix_page_task_run_status')

    op.drop_table('page_task_state')
    with op.batch_alter_table('sheet', schema=None) as batch_op:
        batch_op.drop_index('ix_sheet_number')
        batch_op.drop_index('ix_sheet_document_discipline')

    op.drop_table('sheet')
    with op.batch_alter_table('export_job', schema=None) as batch_op:
        batch_op.drop_index('ix_export_run')
        batch_op.drop_index('ix_export_document_created')

    op.drop_table('export_job')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_run_occurred')
        batch_op.drop_index('ix_audit_entity')
        batch_op.drop_index('ix_audit_document_seq')

    op.drop_table('audit_event')
    with op.batch_alter_table('pipeline_run', schema=None) as batch_op:
        batch_op.drop_index('uq_pipeline_run_current', postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))
        batch_op.drop_index('ix_run_document_created')

    op.drop_table('pipeline_run')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index('ix_document_project')

    op.drop_table('document')
    with op.batch_alter_table('sheet_scale', schema=None) as batch_op:
        batch_op.drop_index('uq_sheet_scale_current', postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))

    op.drop_table('sheet_scale')
    with op.batch_alter_table('review_action', schema=None) as batch_op:
        batch_op.drop_index('ix_review_stable_key')
        batch_op.drop_index('ix_review_run_created')
        batch_op.drop_index('ix_review_line')

    op.drop_table('review_action')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index('ix_project_status_created')

    op.drop_table('project')
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.drop_index('ix_measurement_run_system_size')
        batch_op.drop_index('ix_measurement_run_sheet')

    op.drop_table('measurement')
    # ### end Alembic commands ###
